# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

image: golang:latest

stages:
  - test

test:
  stage: test
  allow_failure: true
  script:
    - apt update 
    - apt install curl
    - curl --version 
    - echo "Waiting for 20 seconds..."
    - sleep 20
    - curl localhost:8081 || true
    - curl docker:8081 || true
    - curl http://gitlab-ce:8081 || true
    #- docker-compose -f docker-compose-test.yml up --exit-code-from=gateway --force-recreate
    # - cd ./httpserv
    # - go get -d -v
    # - go run httpserv.go & disown
    # - cd ..
    # - cd ./gateway
    # - go get -d -v
    # - CGO_ENABLED=0 go test
  
  
    # - go fmt ./gateway ./httpserv ./orig ./obse ./imed | grep -v /vendor/
    # - go vet ./gateway ./httpserv ./orig ./obse ./imed | grep -v /vendor/
    # - go test ./gateway ./httpserv ./orig ./obse ./imed | grep -v /vendor/

