image: golang:1.19

stages:
  - lint
  - unit-test
  - deploy

static-analysis:
  stage: lint
  script:
    - cd ./gateway 
    - go vet
    - cd ..
    - cd ./httpserv
    - go vet
    - cd ..
    - cd ./obse
    - go vet
    - cd ..
    - cd ./imed
    - go vet
    - echo "Linting succesful"

test:
  stage: unit-test
  script:
    - echo "Waiting for 30 seconds..."
    - sleep 30
    - cd ./gateway
    - CGO_ENABLED=0 go test

deploy-job:
  stage: deploy
  image: docker
  services:
  - name: docker:dind
    alias: localhost
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
  environment: production
  script:
    - docker-compose -H $DOCKER_HOST up --build -d
    - echo "Application successfully deployed."

