# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

image: golang:alpine

stages:
  - test

test:
  stage: test
  script:
    - cd ./gateway
    - go get -d -v
    - CGO_ENABLED=0 go test
    # - go fmt ./gateway ./httpserv ./orig ./obse ./imed | grep -v /vendor/
    # - go vet ./gateway ./httpserv ./orig ./obse ./imed | grep -v /vendor/
    # - go test ./gateway ./httpserv ./orig ./obse ./imed | grep -v /vendor/

