# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

# image: docker

# services:
#   - name: docker:dind
#     alias: localhost

# variables:
#   DOCKER_HOST: tcp://docker:2375
#   DOCKER_TLS_CERTDIR: ""
#   DOCKER_DRIVER: overlay2

image: golang:1.19

stages:
  - lint
  - unit-test
  - deploy

static-analysis:
  stage: lint
  script:
    - cd ./gateway 
    - go vet
    - cd ..
    - cd ./httpserv
    - go vet
    - cd ..
    - cd ./obse
    - go vet
    - cd ..
    - cd ./imed
    - go vet
    - echo "Linting succesful"

test:
  stage: unit-test
  script:
    - echo "Waiting for 30 seconds..."
    - sleep 30
    - cd ./gateway
    - CGO_ENABLED=0 go test
    # - docker-compose -f docker-compose-test.yml up --exit-code-from=gateway --force-recreate # This can be used for E2E
    # - cd ./httpserv
    # - go get -d -v
    # - go run httpserv.go & disown
    # - cd ..
    # - cd ./gateway
    # - go get -d -v
    # - CGO_ENABLED=0 go test
  
    # - go fmt ./gateway ./httpserv ./orig ./obse ./imed | grep -v /vendor/
    # - go vet ./gateway ./httpserv ./orig ./obse ./imed | grep -v /vendor/
    # - go test ./gateway ./httpserv ./orig ./obse ./imed | grep -v /vendor/

deploy-job:
  stage: deploy
  image: docker
  services:
  - name: docker:dind
    alias: localhost
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  environment: production
  script:
    - export DOCKER_HOST=unix:///var/run/docker.sock
    - docker-compose -H $DOCKER_HOST up --build
    - echo "Application successfully deployed."

