version: '2.1'

services:
  gateway:
    build: ./gateway
    ports:
      - "8083:8083"
    command: ["CGO_ENABLED=0 go test go /app"]
    depends_on:
      - httpserv

  httpserv:
    build: ./httpserv
    volumes:
      - message-storage:/app
    ports:
      - "8080:8080"
    command: ["go run /httpserv.go"]
  
volumes:
  message-storage: