version: '2.1'

services:
  orig:
    build: ./orig
    depends_on:
      - rabbitmq
      - imed
      - obse
      - httpserv
    links: 
        - rabbitmq
  
  imed:
    build: ./imed
    depends_on:
      rabbitmq:
        condition: service_healthy
    links: 
        - rabbitmq

  obse:
    build: ./obse
    volumes: 
      - message-storage:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    links: 
        - rabbitmq

  httpserv:
    build: ./httpserv
    volumes:
      - message-storage:/app
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    links: 
        - rabbitmq
  
  rabbitmq:
    build: ./rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 3s
      retries: 3
  
volumes:
  message-storage: